import type { UiScenario } from '@/playwright/resources';

export const playwrightUiScenarios: UiScenario[] = [
  {
    id: 'playable-concept-basic',
    title: 'Playable concept creates and previews a generated game scene',
    kind: 'prototype',
    flow: 'standard',
    automated: true,
    description:
      'Validates the primary happy path: create a playable game concept, send one prompt, persist the generated scene HTML, and render it in the preview iframe.',
    create: {
      projectName: 'Game studio automation smoke',
      tab: 'prototype',
    },
    prompt: 'Create a small playable encounter scene',
    mockArtifact: {
      identifier: 'playable-scene-mock',
      title: 'Playable Scene Mock',
      fileName: 'playable-scene-mock.html',
      heading: 'Playable Scene Mock',
      html:
        '<!doctype html><html><body><main><h1>Playable Scene Mock</h1><p>Generated by the AI Game Design Studio Playwright rig.</p></main></body></html>',
    },
    notes: [
      'This is the seed smoke test and should stay fast.',
      'It uses mocked SSE so the UI path stays deterministic.',
    ],
  },
  {
    id: 'deck-basic',
    title: 'Game pitch deck renders a mocked slide artifact',
    kind: 'deck',
    flow: 'standard',
    automated: true,
    description:
      'Covers the game pitch / GDD deck tab in project creation and verifies that a deck artifact lands in the workspace preview.',
    create: {
      projectName: 'Deck automation smoke',
      tab: 'deck',
    },
    prompt: 'Create a short deck with two slides',
    mockArtifact: {
      identifier: 'mock-deck',
      title: 'Mock Deck',
      fileName: 'mock-deck.html',
      heading: 'Mock Deck',
      html:
        '<!doctype html><html><body><section class="slide"><h1>Mock Deck</h1></section></body></html>',
    },
    notes: [
      'Confirms the game pitch deck creation tab still routes into the same generation path.',
    ],
  },
  {
    id: 'comment-attachment-flow',
    title: 'Scene comments attach to chat and send as structured context',
    kind: 'prototype',
    flow: 'comment-attachment-flow',
    automated: true,
    description:
      'Exercises scene comment mode: save a latest gameplay element comment, attach/remove it from the composer, and send it as an empty visible prompt with structured comment context.',
    create: {
      projectName: 'Scene comment attachment flow',
      tab: 'prototype',
    },
    prompt: 'Create a commentable gameplay preview',
    mockArtifact: {
      identifier: 'commentable-artifact',
      title: 'Commentable Encounter',
      fileName: 'commentable-artifact.html',
      heading: 'Encounter readability headline',
      html:
        '<!doctype html><html><body><main data-agds-id="encounter-section"><h1 data-agds-id="encounter-title" data-screen-label="Encounter title">Encounter readability headline</h1><p data-agds-id="encounter-copy">HUD readability note for comment mode.</p></main></body></html>',
    },
    notes: [
      'The composer textarea stays empty; selected gameplay preview comments are sent through commentAttachments.',
    ],
  },
  {
    id: 'game-art-bible-selection',
    title: 'Selecting a game art bible carries through project creation',
    kind: 'prototype',
    flow: 'game-art-bible-selection',
    automated: true,
    description:
      'Verifies that a chosen game art bible is selectable in the new-project panel and remains visible in project metadata after creation.',
    create: {
      projectName: 'Game art bible selection',
      tab: 'prototype',
    },
    prompt: 'Create a small tactical HUD concept',
    notes: [
      'Uses a mocked game-art-bible list so the picker stays deterministic across environments.',
      'Focuses on creation and metadata persistence instead of generation output.',
    ],
  },
  {
    id: 'example-use-prompt',
    title: 'Using an example prompt creates a project with a seeded draft',
    kind: 'prototype',
    flow: 'example-use-prompt',
    automated: true,
    description:
      'Verifies the Examples tab fast path: click Use this prompt, create a project immediately, and carry the example prompt into the chat composer.',
    create: {
      projectName: 'Game example prompt project',
      tab: 'prototype',
    },
    prompt: 'Draft a cozy mobile main menu and first-run gameplay flow for a casual adventure game',
    notes: [
      'Uses a mocked skills list so the examples gallery stays deterministic.',
      'Targets the pendingPrompt fast-create path instead of the standard game project form.',
    ],
  },
  {
    id: 'conversation-persistence',
    title: 'Conversation history survives refresh and switching',
    kind: 'workspace',
    flow: 'conversation-persistence',
    automated: true,
    description:
      'Exercises conversation creation, persistence, refresh reload, and switching between threads in one project.',
    create: {
      projectName: 'Conversation persistence',
      tab: 'prototype',
    },
    prompt: 'Create a small playable scene artifact',
    secondaryPrompt: 'Create another encounter artifact in a fresh conversation',
    mockArtifact: {
      identifier: 'playable-scene-mock',
      title: 'Playable Scene Mock',
      fileName: 'playable-scene-mock.html',
      heading: 'Playable Scene Mock',
      html:
        '<!doctype html><html><body><main><h1>Playable Scene Mock</h1><p>Generated by the AI Game Design Studio Playwright rig.</p></main></body></html>',
    },
    notes: [
      'Should use the same mock SSE flow as the playable concept smoke path.',
      'Reload should keep the original conversation content available from the history menu.',
    ],
  },
  {
    id: 'file-mention',
    title: 'Reference files can be mentioned and sent back to the agent',
    kind: 'workspace',
    flow: 'file-mention',
    automated: true,
    description:
      'Validates the upload, staged attachment, and @ mention flow inside the game studio chat composer.',
    create: {
      projectName: 'Reference file mention flow',
      tab: 'prototype',
    },
    prompt: 'Review @reference.txt and use it as game design context',
    notes: [
      'Seeds a tiny game reference fixture through the project file API, then exercises the composer mention flow.',
    ],
  },
  {
    id: 'deep-link-preview',
    title: 'Deep-linking to a file route opens the expected scene preview tab',
    kind: 'workspace',
    flow: 'deep-link-preview',
    automated: true,
    description:
      'Verifies that /projects/:id/files/:name restores the matching open tab and game preview frame after navigation or refresh.',
    create: {
      projectName: 'Deep link preview',
      tab: 'prototype',
    },
    prompt: 'Create a small playable scene artifact',
    mockArtifact: {
      identifier: 'playable-scene-mock',
      title: 'Playable Scene Mock',
      fileName: 'playable-scene-mock.html',
      heading: 'Playable Scene Mock',
      html:
        '<!doctype html><html><body><main><h1>Playable Scene Mock</h1><p>Generated by the AI Game Design Studio Playwright rig.</p></main></body></html>',
    },
    notes: [
      'Can reuse the generated HTML from the playable concept smoke path, then revisit with a routed URL.',
    ],
  },
  {
    id: 'file-upload-send',
    title: 'Composer file picker uploads a file and sends it with the prompt',
    kind: 'workspace',
    flow: 'file-upload-send',
    automated: true,
    description:
      'Exercises the real attach button and hidden file input, then verifies the staged file is sent and shown back on the user message.',
    create: {
      projectName: 'File upload send flow',
      tab: 'prototype',
    },
    prompt: 'Use the uploaded game reference as context',
    notes: [
      'Uses Playwright setInputFiles on the hidden composer picker instead of seeding through the game file API.',
    ],
  },
  {
    id: 'game-files-upload',
    title: 'Studio Files panel uploads an image and opens it in the workspace',
    kind: 'workspace',
    flow: 'game-files-upload',
    automated: true,
    description:
      'Exercises the Studio Files upload flow in the workspace, then verifies the uploaded image can be previewed and opened as a tab.',
    create: {
      projectName: 'Studio files upload flow',
      tab: 'prototype',
    },
    prompt: 'Upload an image through the studio files browser',
    notes: [
      'Uses the FileWorkspace upload input rather than the chat composer upload path.',
    ],
  },
  {
    id: 'game-files-delete',
    title: 'Studio Files panel deletes an uploaded file and clears its tab',
    kind: 'workspace',
    flow: 'game-files-delete',
    automated: true,
    description:
      'Uploads a file through the Studio Files panel, deletes it from the row menu, and verifies it disappears from both the list and open tabs.',
    create: {
      projectName: 'Studio files delete flow',
      tab: 'prototype',
    },
    prompt: 'Delete an uploaded image through the studio files browser',
    notes: [
      'Builds on the same workspace file flow as the studio upload scenario, then verifies cleanup behavior.',
    ],
  },
  {
    id: 'game-files-tab-persistence',
    title: 'Open file tabs survive refresh with the correct active tab',
    kind: 'workspace',
    flow: 'game-files-tab-persistence',
    automated: true,
    description:
      'Uploads multiple files through the Studio Files flow, switches the active tab, reloads the page, and verifies both the tab set and selected tab are restored.',
    create: {
      projectName: 'Studio files tab persistence',
      tab: 'prototype',
    },
    prompt: 'Restore open file tabs after refresh',
    notes: [
      'Covers the persisted tabs state stored by ProjectView and restored by FileWorkspace.',
    ],
  },
  {
    id: 'conversation-delete-recovery',
    title: 'Deleting the active conversation falls back cleanly',
    kind: 'workspace',
    flow: 'conversation-delete-recovery',
    automated: true,
    description:
      'Creates multiple conversations, deletes the active one, and verifies the UI falls back to the remaining thread instead of getting stuck.',
    create: {
      projectName: 'Conversation delete recovery',
      tab: 'prototype',
    },
    prompt: 'Create a small playable scene artifact',
    secondaryPrompt: 'Create another encounter artifact before deleting this thread',
    mockArtifact: {
      identifier: 'playable-scene-mock',
      title: 'Playable Scene Mock',
      fileName: 'playable-scene-mock.html',
      heading: 'Playable Scene Mock',
      html:
        '<!doctype html><html><body><main><h1>Playable Scene Mock</h1><p>Generated by the AI Game Design Studio Playwright rig.</p></main></body></html>',
    },
    notes: [
      'Confirms the project still has a live conversation after deleting the current thread.',
    ],
  },
  {
    id: 'question-form-selection-limit',
    title: 'Discovery brief checkbox limits block selecting more than the allowed maximum',
    kind: 'workspace',
    flow: 'question-form-selection-limit',
    automated: true,
    description:
      'Verifies that a game discovery brief question with maxSelections=2 cannot be pushed past two selected options.',
    create: {
      projectName: 'Game discovery brief selection limit',
      tab: 'prototype',
    },
    prompt: 'Help me plan a cozy tavern tutorial scene',
    notes: [
      'Mocks a discovery brief response instead of an artifact so the test can exercise the inline clarifying UI.',
      'Confirms both the interaction guard and the rendered checked state stay capped at two options.',
    ],
  },
  {
    id: 'question-form-submit-persistence',
    title: 'Discovery brief answers persist into chat history and reload in a locked state',
    kind: 'workspace',
    flow: 'question-form-submit-persistence',
    automated: true,
    description:
      'Verifies that answering a game discovery brief writes a user follow-up message, then rehydrates the form in an answered and locked state after reload.',
    create: {
      projectName: 'Game discovery brief submit persistence',
      tab: 'prototype',
    },
    prompt: 'Plan a compact tavern management tutorial scene',
    notes: [
      'Mocks an inline discovery brief on the first assistant turn and a plain acknowledgment on the follow-up turn.',
      'Confirms the answered state survives a full page reload instead of relying only on local submit state.',
    ],
  },
  {
    id: 'generation-does-not-create-extra-file',
    title: 'Generated game artifacts stay stable when no new prompt is sent',
    kind: 'workspace',
    flow: 'generation-does-not-create-extra-file',
    automated: true,
    description:
      'Generates one game scene HTML artifact, then verifies reload and idle time do not create any additional project files without a new player-facing prompt.',
    create: {
      projectName: 'No extra generated game file',
      tab: 'prototype',
    },
    prompt: 'Create one main-menu artifact',
    mockArtifact: {
      identifier: 'stable-artifact',
      title: 'Stable Game Scene',
      fileName: 'stable-artifact.html',
      heading: 'Stable Game Scene',
      html:
        '<!doctype html><html><body><main><h1>Stable Game Scene</h1><p>Only one game artifact should exist.</p></main></body></html>',
    },
    notes: [
      'Targets the trust-sensitive bug where a game project can appear to generate a fresh file on its own.',
      'Uses the files API after reload to assert the project file set is unchanged.',
    ],
  },
  {
    id: 'deck-pagination-next-prev-correctness',
    title: 'Game pitch deck previous and next controls move in the correct direction',
    kind: 'deck',
    flow: 'deck-pagination-next-prev-correctness',
    automated: true,
    description:
      'Should verify that game pitch deck pagination moves to the actual previous and next slide instead of routing both actions to the same page.',
    create: {
      projectName: 'Deck pagination controls',
      tab: 'deck',
    },
    prompt: 'Review pagination behavior in a multi-slide deck preview',
    notes: [
      'Seeds deterministic deck HTML through the project files API and verifies previous/next controls in Playwright.',
    ],
  },
  {
    id: 'deck-pagination-per-file-isolated',
    title: 'Each game pitch deck tab preserves its own pagination state',
    kind: 'deck',
    flow: 'deck-pagination-per-file-isolated',
    automated: true,
    description:
      'Should verify that switching between multiple game deck HTML files does not leak page position across tabs or reset both files to page 1.',
    create: {
      projectName: 'Deck pagination isolation',
      tab: 'deck',
    },
    prompt: 'Keep pagination state isolated per generated deck file',
    notes: [
      'Seeds two deterministic deck HTML files and verifies each open tab preserves its own active slide.',
    ],
  },
  {
    id: 'uploaded-image-renders-in-preview',
    title: 'Uploaded key art references render correctly in generated deck preview',
    kind: 'workspace',
    flow: 'uploaded-image-renders-in-preview',
    automated: true,
    description:
      'Should verify that uploaded game reference images resolve to loadable src paths inside generated HTML instead of rendering as broken images.',
    create: {
      projectName: 'Uploaded key art preview render',
      tab: 'prototype',
    },
    prompt: 'Use uploaded key art references inside a generated deck preview',
    notes: [
      'Seeds an image plus relative HTML reference and asserts the preview iframe loads the image.',
    ],
  },
  {
    id: 'python-source-preview',
    title: 'Python files should open with a readable inline source preview',
    kind: 'workspace',
    flow: 'python-source-preview',
    automated: true,
    description:
      'Should verify that opening a .py file in the main workspace renders a readable source/code preview instead of an unsupported blank state.',
    create: {
      projectName: 'Python source preview',
      tab: 'prototype',
    },
    prompt: 'Open a generated Python file and inspect its source inline',
    notes: [
      'Seeds a deterministic .py file through the project files API, opens it from the file list, and asserts the source viewer renders readable code text.',
    ],
  },
];
