import type { WizardState } from './useWizardState';

function esc(text: string): string {
  return text.replace(/[\\`*_{}[\]()#+\-.!|]/g, (c) => `\\${c}`);
}

function statBar(value: number, max = 100): string {
  const filled = Math.round((value / max) * 10);
  return `${'█'.repeat(filled)}${'░'.repeat(10 - filled)} ${value}/${max}`;
}

export function compileGDDMarkdown(state: WizardState): string {
  const { concept, screens, flows, characters, worldNotes, worldBoardHtml, prototypeHtml, exportEngine } = state;
  const gameName = concept.name.trim() || 'Untitled Game';
  const now = new Date().toISOString().split('T')[0];
  const lines: string[] = [];

  // Header
  lines.push(`# Game Design Document — ${esc(gameName)}`);
  lines.push('');
  lines.push(`> Generated by Greybox Studio · ${now}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // 1. Overview
  lines.push('## 1. Overview');
  lines.push('');
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| **Game Name** | ${esc(gameName)} |`);
  lines.push(`| **Game Type** | ${esc(concept.gameType)} |`);
  lines.push(`| **Genre** | ${esc(concept.genre || '—')} |`);
  lines.push(`| **Platform** | ${esc(concept.platform || '—')} |`);
  lines.push(`| **Art Style** | ${esc(concept.artStyle || '—')} |`);
  lines.push(`| **Target Audience** | ${esc(concept.targetAudience || '—')} |`);
  lines.push('');
  if (concept.coreLoop) {
    lines.push('### Core Loop');
    lines.push('');
    lines.push(concept.coreLoop);
    lines.push('');
  }
  if (concept.aiSummary) {
    lines.push('### AI-Generated Summary');
    lines.push('');
    lines.push(concept.aiSummary);
    lines.push('');
  }
  lines.push('---');
  lines.push('');

  // 2. Screen Flow
  lines.push('## 2. Screen Flow');
  lines.push('');
  if (screens.length === 0) {
    lines.push('_No screens defined._');
  } else {
    lines.push('### Screens');
    lines.push('');
    for (const screen of screens) {
      const components = screen.components.length > 0
        ? screen.components.map((c) => c.name).join(', ')
        : 'No components';
      lines.push(`- **${esc(screen.name)}** *(${screen.kind})* — ${components}`);
    }
    if (flows.length > 0) {
      lines.push('');
      lines.push('### Transitions');
      lines.push('');
      for (const flow of flows) {
        const from = screens.find((s) => s.id === flow.fromId)?.name ?? flow.fromId;
        const to = screens.find((s) => s.id === flow.toId)?.name ?? flow.toId;
        const label = flow.label ? ` *(${esc(flow.label)})*` : '';
        lines.push(`- ${esc(from)} → ${esc(to)}${label}`);
      }
    }
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  // 3. Visual Design
  lines.push('## 3. Visual Design');
  lines.push('');
  const screensWithMockup = screens.filter((s) => s.mockupHtml);
  if (screensWithMockup.length === 0) {
    lines.push('_No design mockups generated._');
  } else {
    lines.push(`${screensWithMockup.length} screen mockup(s) were generated in Greybox Studio.`);
    lines.push('');
    for (const screen of screensWithMockup) {
      lines.push(`### ${esc(screen.name)}`);
      lines.push('');
      lines.push('> Mockup available in Greybox Studio (HTML/CSS live preview).');
      lines.push('');
    }
  }
  lines.push('---');
  lines.push('');

  // 4. Characters
  lines.push('## 4. Characters');
  lines.push('');
  if (characters.length === 0) {
    lines.push('_No characters defined._');
  } else {
    for (const char of characters) {
      lines.push(`### ${esc(char.name)} *(${char.type})*`);
      lines.push('');
      if (char.description) {
        lines.push(char.description);
        lines.push('');
      }
      lines.push('**Stats**');
      lines.push('');
      lines.push(`- HP:     ${statBar(char.stats.hp)}`);
      lines.push(`- Speed:  ${statBar(char.stats.speed)}`);
      lines.push(`- Damage: ${statBar(char.stats.damage)}`);
      lines.push('');
      if (char.assetUrl) {
        lines.push(`**3D Model:** [View](${char.assetUrl})`);
        lines.push('');
      } else if (char.spriteUrl) {
        lines.push(`**2D Sprite:** [View](${char.spriteUrl})`);
        lines.push('');
      }
    }
  }
  lines.push('---');
  lines.push('');

  // 5. World
  lines.push('## 5. World');
  lines.push('');
  if (worldNotes) {
    lines.push(worldNotes);
    lines.push('');
  }
  if (worldBoardHtml) {
    lines.push('> World board generated in Greybox Studio (HTML/CSS live preview).');
    lines.push('');
  }
  if (!worldNotes && !worldBoardHtml) {
    lines.push('_No world description defined._');
    lines.push('');
  }
  lines.push('---');
  lines.push('');

  // 6. Prototype
  lines.push('## 6. Prototype');
  lines.push('');
  if (prototypeHtml) {
    lines.push('An interactive prototype was generated in Greybox Studio.');
    lines.push('Open this project in Greybox Studio to view and share the live prototype.');
  } else {
    lines.push('_No prototype generated._');
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  // 7. Tech Spec
  lines.push('## 7. Tech Spec');
  lines.push('');
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| **Target Engine** | ${esc(exportEngine ?? 'Not selected')} |`);
  lines.push(`| **Game Type** | ${esc(concept.gameType)} |`);
  const engineGuide: Record<string, string> = {
    unity: 'Unity 2022.3 LTS+ with Greybox Unity Plugin',
    godot: 'Godot 4.0+ with Greybox Godot Plugin',
    unreal: 'Unreal Engine 5.3+ with Greybox UE Plugin (coming soon)',
    webgl: 'HTML5/WebGL — no engine required',
  };
  if (exportEngine && engineGuide[exportEngine]) {
    lines.push(`| **Deployment** | ${engineGuide[exportEngine]} |`);
  }
  lines.push('');

  return lines.join('\n');
}

export function downloadGDDMarkdown(state: WizardState): void {
  const gameName = (state.concept.name.trim() || 'game-design').toLowerCase().replace(/[^a-z0-9]+/g, '-');
  const md = compileGDDMarkdown(state);
  const blob = new Blob([md], { type: 'text/markdown; charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${gameName}-gdd.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
