// Proprietary and confidential. Copyright (c) 2026 Greybox Studio.

import type { PlaytestPersona } from '../types.js';

export const defaultPersonas: PlaytestPersona[] = [
  {
    id: 'speedrunner',
    name: 'Speedrunner',
    description: 'Routes aggressively, skips optional content, and pressures timers.',
    primaryGoal: 'Finish as quickly as possible.',
    inputStyle: 'precision',
    patience: 0.55,
    riskTolerance: 0.92,
    thoroughness: 0.18,
    tags: ['route-break', 'timer-pressure'],
  },
  {
    id: 'completionist',
    name: 'Completionist',
    description: 'Searches every branch and tracks missed collectibles.',
    primaryGoal: 'Find everything before finishing.',
    inputStyle: 'completionist',
    patience: 0.9,
    riskTolerance: 0.52,
    thoroughness: 0.96,
    tags: ['secrets', 'coverage'],
  },
  {
    id: 'casual',
    name: 'Casual',
    description: 'Reads the screen slowly and favors obvious objectives.',
    primaryGoal: 'Understand the game without external instruction.',
    inputStyle: 'casual',
    patience: 0.72,
    riskTolerance: 0.38,
    thoroughness: 0.48,
    tags: ['readability', 'onboarding'],
  },
  {
    id: 'rage-quitter',
    name: 'Rage Quitter',
    description: 'Low tolerance for repeated failure, unclear UI, or long resets.',
    primaryGoal: 'Leave when friction feels unfair.',
    inputStyle: 'chaotic',
    patience: 0.22,
    riskTolerance: 0.66,
    thoroughness: 0.21,
    tags: ['frustration', 'retention'],
  },
  {
    id: 'explorer',
    name: 'Explorer',
    description: 'Checks edges, backtracks, and tries alternate paths.',
    primaryGoal: 'Understand the space and uncover hidden routes.',
    inputStyle: 'exploratory',
    patience: 0.82,
    riskTolerance: 0.62,
    thoroughness: 0.84,
    tags: ['map-coverage', 'softlock'],
  },
  {
    id: 'lore-hunter',
    name: 'Lore Hunter',
    description: 'Pauses for narrative objects, flavor text, and environmental clues.',
    primaryGoal: 'Read the story through the level.',
    inputStyle: 'exploratory',
    patience: 0.88,
    riskTolerance: 0.42,
    thoroughness: 0.78,
    tags: ['narrative', 'readability'],
  },
  {
    id: 'optimizer',
    name: 'Optimizer',
    description: 'Tests reward loops, economy pacing, and upgrade efficiency.',
    primaryGoal: 'Find the strongest repeatable strategy.',
    inputStyle: 'optimization',
    patience: 0.74,
    riskTolerance: 0.58,
    thoroughness: 0.7,
    tags: ['balance', 'economy'],
  },
  {
    id: 'button-masher',
    name: 'Button Masher',
    description: 'Inputs rapidly and exposes state bugs around animation locks.',
    primaryGoal: 'Brute-force feedback and control recovery.',
    inputStyle: 'chaotic',
    patience: 0.46,
    riskTolerance: 0.86,
    thoroughness: 0.25,
    tags: ['input-buffering', 'animation-lock'],
  },
  {
    id: 'stealth-only',
    name: 'Stealth Only',
    description: 'Avoids direct combat and looks for silent bypasses.',
    primaryGoal: 'Complete without being detected.',
    inputStyle: 'stealth',
    patience: 0.8,
    riskTolerance: 0.28,
    thoroughness: 0.68,
    tags: ['alternate-route', 'ai-vision'],
  },
  {
    id: 'achievement-chaser',
    name: 'Achievement Chaser',
    description: 'Attempts unusual constraints to unlock meta goals.',
    primaryGoal: 'Trigger optional achievements and edge objectives.',
    inputStyle: 'completionist',
    patience: 0.76,
    riskTolerance: 0.72,
    thoroughness: 0.88,
    tags: ['achievements', 'edge-cases'],
  },
];

export function personasForAlpha(): PlaytestPersona[] {
  return defaultPersonas.slice();
}
