// Proprietary and confidential. Copyright (c) 2026 Greybox Studio.

namespace Greybox.Editor.McpBridge
{
    public static class McpToolDefinitions
    {
        public static readonly string[] ToolNames =
        {
            "unity.getSceneHierarchy",
            "unity.createGameObject",
            "unity.addComponent",
            "unity.setField",
            "unity.assignAsset",
            "unity.runEditModeTest",
            "unity.captureGameViewScreenshot",
            "unity.buildAddressables"
        };

        public static string ToolsJson()
        {
            return @"{
  ""tools"": [
    { ""name"": ""unity.getSceneHierarchy"", ""annotations"": { ""title"": ""Get Scene Hierarchy"", ""readOnlyHint"": true, ""destructiveHint"": false, ""idempotentHint"": true, ""openWorldHint"": false }, ""inputSchema"": { ""type"": ""object"", ""properties"": {}, ""additionalProperties"": false } },
    { ""name"": ""unity.createGameObject"", ""annotations"": { ""title"": ""Create GameObject"", ""readOnlyHint"": false, ""destructiveHint"": false, ""idempotentHint"": false, ""openWorldHint"": false }, ""inputSchema"": { ""type"": ""object"", ""additionalProperties"": false, ""$defs"": { ""vector3"": { ""oneOf"": [ { ""type"": ""object"", ""required"": [""x"", ""y"", ""z""], ""additionalProperties"": false, ""properties"": { ""x"": { ""type"": ""number"" }, ""y"": { ""type"": ""number"" }, ""z"": { ""type"": ""number"" } } }, { ""type"": ""array"", ""minItems"": 3, ""maxItems"": 3, ""items"": { ""type"": ""number"" } } ] } }, ""properties"": { ""name"": { ""type"": ""string"", ""minLength"": 1, ""maxLength"": 128, ""pattern"": ""^(?!\\s*$)(?!.*[\\x00-\\x1F\\x7F-\\x9F]).+$"" }, ""parent"": { ""type"": ""string"", ""minLength"": 1, ""maxLength"": 512, ""pattern"": ""^(?!\\s*$)(?!.*[\\x00-\\x1F\\x7F-\\x9F]).+$"" }, ""parentId"": { ""type"": ""string"", ""minLength"": 1, ""maxLength"": 512, ""pattern"": ""^(?!\\s*$)(?!.*[\\x00-\\x1F\\x7F-\\x9F]).+$"" }, ""position"": { ""description"": ""Local Vector3 as {x,y,z} or [x,y,z]"", ""$ref"": ""#/$defs/vector3"" }, ""rotation"": { ""description"": ""Local Euler Vector3 as {x,y,z} or [x,y,z]"", ""$ref"": ""#/$defs/vector3"" }, ""scale"": { ""description"": ""Local Vector3 as {x,y,z} or [x,y,z]"", ""$ref"": ""#/$defs/vector3"" } }, ""required"": [""name""] } },
    { ""name"": ""unity.addComponent"", ""annotations"": { ""title"": ""Add Component"", ""readOnlyHint"": false, ""destructiveHint"": false, ""idempotentHint"": false, ""openWorldHint"": false }, ""inputSchema"": { ""type"": ""object"", ""additionalProperties"": false, ""properties"": { ""gameObjectId"": { ""type"": ""string"", ""minLength"": 1, ""maxLength"": 512, ""pattern"": ""^(?!\\s*$)(?!.*[\\x00-\\x1F\\x7F-\\x9F]).+$"" }, ""componentType"": { ""type"": ""string"", ""minLength"": 1, ""maxLength"": 512, ""pattern"": ""^(?!\\s*$)(?!.*[\\x00-\\x1F\\x7F-\\x9F]).+$"" } }, ""required"": [""gameObjectId"", ""componentType""] } },
    { ""name"": ""unity.setField"", ""annotations"": { ""title"": ""Set Field"", ""readOnlyHint"": false, ""destructiveHint"": false, ""idempotentHint"": false, ""openWorldHint"": false }, ""inputSchema"": { ""type"": ""object"", ""additionalProperties"": false, ""$defs"": { ""vector3"": { ""oneOf"": [ { ""type"": ""object"", ""required"": [""x"", ""y"", ""z""], ""additionalProperties"": false, ""properties"": { ""x"": { ""type"": ""number"" }, ""y"": { ""type"": ""number"" }, ""z"": { ""type"": ""number"" } } }, { ""type"": ""array"", ""minItems"": 3, ""maxItems"": 3, ""items"": { ""type"": ""number"" } } ] }, ""color"": { ""oneOf"": [ { ""type"": ""string"", ""pattern"": ""^#?[0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?$"" }, { ""type"": ""object"", ""required"": [""r"", ""g"", ""b""], ""additionalProperties"": false, ""properties"": { ""r"": { ""type"": ""number"" }, ""g"": { ""type"": ""number"" }, ""b"": { ""type"": ""number"" }, ""a"": { ""type"": ""number"" } } }, { ""type"": ""array"", ""minItems"": 3, ""maxItems"": 4, ""items"": { ""type"": ""number"" } } ] } }, ""properties"": { ""gameObjectId"": { ""type"": ""string"", ""minLength"": 1, ""maxLength"": 512, ""pattern"": ""^(?!\\s*$)(?!.*[\\x00-\\x1F\\x7F-\\x9F]).+$"" }, ""componentType"": { ""description"": ""Unity component type, or UnityEngine.GameObject for tag/layer/isStatic/activeSelf metadata"", ""type"": ""string"", ""minLength"": 1, ""maxLength"": 512, ""pattern"": ""^(?!\\s*$)(?!.*[\\x00-\\x1F\\x7F-\\x9F]).+$"" }, ""fieldName"": { ""type"": ""string"", ""minLength"": 1, ""maxLength"": 128, ""pattern"": ""^(?!\\s*$)(?!.*[\\x00-\\x1F\\x7F-\\x9F]).+$"" }, ""value"": { ""oneOf"": [ { ""type"": ""string"", ""maxLength"": 4096 }, { ""type"": ""array"", ""maxItems"": 64, ""items"": { ""type"": ""string"", ""maxLength"": 256, ""pattern"": ""^(?!.*[\\x00-\\x1F\\x7F-\\x9F]).*$"" } }, { ""type"": ""number"" }, { ""type"": ""boolean"" }, { ""$ref"": ""#/$defs/vector3"" }, { ""$ref"": ""#/$defs/color"" } ] } }, ""required"": [""gameObjectId"", ""componentType"", ""fieldName"", ""value""] } },
    { ""name"": ""unity.assignAsset"", ""annotations"": { ""title"": ""Assign Asset"", ""readOnlyHint"": false, ""destructiveHint"": false, ""idempotentHint"": false, ""openWorldHint"": false }, ""inputSchema"": { ""type"": ""object"", ""additionalProperties"": false, ""properties"": { ""gameObjectId"": { ""type"": ""string"", ""minLength"": 1, ""maxLength"": 512, ""pattern"": ""^(?!\\s*$)(?!.*[\\x00-\\x1F\\x7F-\\x9F]).+$"" }, ""componentType"": { ""type"": ""string"", ""minLength"": 1, ""maxLength"": 512, ""pattern"": ""^(?!\\s*$)(?!.*[\\x00-\\x1F\\x7F-\\x9F]).+$"" }, ""fieldName"": { ""type"": ""string"", ""minLength"": 1, ""maxLength"": 128, ""pattern"": ""^(?!\\s*$)(?!.*[\\x00-\\x1F\\x7F-\\x9F]).+$"" }, ""assetPath"": { ""type"": ""string"", ""minLength"": 8, ""maxLength"": 512, ""pattern"": ""^(?!.*[\\x00-\\x1F\\x7F-\\x9F])Assets/(?!.*//)(?!.*\\\\)(?!.*(?:^|/)\\.\\.?(?:/|$)).+$"" } }, ""required"": [""gameObjectId"", ""componentType"", ""fieldName"", ""assetPath""] } },
    { ""name"": ""unity.runEditModeTest"", ""annotations"": { ""title"": ""Run EditMode Test"", ""readOnlyHint"": false, ""destructiveHint"": false, ""idempotentHint"": false, ""openWorldHint"": false }, ""inputSchema"": { ""type"": ""object"", ""additionalProperties"": false, ""properties"": { ""testName"": { ""type"": ""string"", ""minLength"": 1, ""maxLength"": 256, ""pattern"": ""^(?!\\s*$)(?!.*[\\x00-\\x1F\\x7F-\\x9F]).+$"" } }, ""required"": [""testName""] } },
    { ""name"": ""unity.captureGameViewScreenshot"", ""annotations"": { ""title"": ""Capture Game View Screenshot"", ""readOnlyHint"": false, ""destructiveHint"": false, ""idempotentHint"": false, ""openWorldHint"": false }, ""inputSchema"": { ""type"": ""object"", ""additionalProperties"": false, ""properties"": { ""width"": { ""type"": ""integer"", ""minimum"": 64, ""maximum"": 4096 }, ""height"": { ""type"": ""integer"", ""minimum"": 64, ""maximum"": 4096 } }, ""required"": [""width"", ""height""] } },
    { ""name"": ""unity.buildAddressables"", ""annotations"": { ""title"": ""Build Addressables"", ""readOnlyHint"": false, ""destructiveHint"": false, ""idempotentHint"": false, ""openWorldHint"": false }, ""inputSchema"": { ""type"": ""object"", ""properties"": {}, ""additionalProperties"": false } }
  ]
}";
        }
    }
}
