import { gameViewportDocumentSchema } from '@ai-game-design-studio/contracts/game-studio';
import type { GameViewportDocument } from '@ai-game-design-studio/contracts/api/files';
import type {
  GameEngineRuntimeGeneratedFile,
  GameEngineRuntimeRequest,
  GameEngineRuntimeResponse,
  GameEngineRuntimeRequestEngine,
} from '@ai-game-design-studio/contracts/api/projects';

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function cleanString(value: unknown, maxLength: number): string | undefined {
  if (typeof value !== 'string') return undefined;
  const clean = value.replace(/\0/g, '').trim();
  return clean ? clean.slice(0, maxLength) : undefined;
}

export function normalizeGameEngineRuntimeRequest(input: unknown): GameEngineRuntimeRequest {
  const source = isRecord(input) ? input : {};
  const fileName = cleanString(source.fileName, 240);
  const engine = normalizeRuntimeEngine(source.engine);
  const writeFileName = cleanString(source.writeFileName, 240);
  const packageDirectory = cleanString(source.packageDirectory, 240);
  return {
    ...(fileName ? { fileName } : {}),
    ...(engine ? { engine } : {}),
    ...(writeFileName && (engine ?? 'webgl') === 'webgl' && /\.html?$/i.test(writeFileName) ? { writeFileName } : {}),
    ...(typeof source.writePackage === 'boolean' ? { writePackage: source.writePackage } : {}),
    ...(packageDirectory ? { packageDirectory } : {}),
  };
}

function normalizeRuntimeEngine(value: unknown): GameEngineRuntimeRequestEngine | undefined {
  const clean = cleanString(value, 32)?.toLowerCase();
  if (clean === 'webgl' || clean === 'webgl-canvas') return 'webgl';
  if (clean === 'unity') return 'unity';
  if (clean === 'godot') return 'godot';
  if (clean === 'unreal' || clean === 'unreal-engine') return 'unreal';
  if (clean === 'native' || clean === 'native-package' || clean === 'engine-package') return 'native-package';
  return undefined;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function safeJsonForScript(value: unknown): string {
  return JSON.stringify(value)
    .replace(/</g, '\\u003c')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

function countTerrainColliders(document: GameViewportDocument): number {
  return (
    (document.terrainZones?.length ?? 0) +
    (document.terrainPaintStrokes?.length ?? 0) +
    (document.terrainSculptPatches?.length ?? 0)
  );
}

function safeIdentifier(value: string): string {
  const clean = value.replace(/[^A-Za-z0-9_]+/g, '_').replace(/^_+|_+$/g, '');
  return clean || 'GameViewRuntime';
}

function sourceBaseName(fileName: string): string {
  return safeIdentifier(fileName.replace(/\.[^.]+(?:\.json)?$/i, ''));
}

function csString(value: unknown): string {
  return JSON.stringify(String(value ?? '')).replace(/\\"/g, '\\"');
}

function gdString(value: unknown): string {
  return JSON.stringify(String(value ?? ''));
}

function cppString(value: unknown): string {
  return JSON.stringify(String(value ?? ''));
}

function nativeRuntimeHooks(engine: GameEngineRuntimeRequestEngine): string[] {
  if (engine === 'unity') {
    return [
      'AGDSGameViewRuntime.TerrainHeightAt(Vector2 position)',
      'AGDSGameViewRuntime.TerrainCollisionAt(Vector2 position)',
      'AGDSGameViewRuntime.AdvanceWorldTick(float deltaTime)',
    ];
  }
  if (engine === 'godot') {
    return [
      'AGDSGameViewRuntime.terrain_height_at(position: Vector2)',
      'AGDSGameViewRuntime.terrain_collision_at(position: Vector2)',
      'AGDSGameViewRuntime.advance_world_tick(delta: float)',
    ];
  }
  if (engine === 'unreal') {
    return [
      'UAGDSGameViewRuntimeComponent::TerrainHeightAt(FVector2D Position)',
      'UAGDSGameViewRuntimeComponent::TerrainCollisionAt(FVector2D Position)',
      'UAGDSGameViewRuntimeComponent::AdvanceWorldTick(float DeltaTime)',
    ];
  }
  return [
    'Unity: AGDSGameViewRuntime.TerrainHeightAt / TerrainCollisionAt / AdvanceWorldTick',
    'Godot: AGDSGameViewRuntime.terrain_height_at / terrain_collision_at / advance_world_tick',
    'Unreal: UAGDSGameViewRuntimeComponent TerrainHeightAt / TerrainCollisionAt / AdvanceWorldTick',
  ];
}

function buildUnityRuntimeFile(document: GameViewportDocument, fileName: string): GameEngineRuntimeGeneratedFile {
  const zones = document.terrainZones ?? [];
  const patches = document.terrainSculptPatches ?? [];
  const factionTerritory = document.worldSimulation?.factionTerritory ?? [];
  const dynamicEvents = document.dynamicEvents ?? [];
  const content = `using System;
using System.Collections.Generic;
using UnityEngine;

// Generated by AI Game Design Studio from ${fileName}. Attach this component to a scene controller.
public sealed class AGDSGameViewRuntime : MonoBehaviour
{
    [Serializable] public struct TerrainZone { public string id; public string type; public float x; public float y; public float w; public float h; }
    [Serializable] public struct SculptPatch { public string id; public float x; public float y; public float radius; public float height; public string falloff; }
    [Serializable] public struct TerrainCollision { public bool blocked; public string zoneId; public float height; }

    public float Tick { get; private set; }
    public string ActiveWeather = ${csString(document.worldSimulation?.weather ?? 'clear')};
    public string ActiveDynamicEvent = "";
    public readonly Dictionary<string, float> FactionControl = new Dictionary<string, float>();

    private readonly TerrainZone[] terrainZones = new TerrainZone[] {
${zones.map((zone) => `        new TerrainZone { id = ${csString(zone.id)}, type = ${csString(zone.type)}, x = ${Number(zone.x ?? 0)}f, y = ${Number(zone.y ?? 0)}f, w = ${Number(zone.w ?? 0)}f, h = ${Number(zone.h ?? 0)}f },`).join('\n')}
    };

    private readonly SculptPatch[] sculptPatches = new SculptPatch[] {
${patches.map((patch) => `        new SculptPatch { id = ${csString(patch.id)}, x = ${Number(patch.x ?? 0)}f, y = ${Number(patch.y ?? 0)}f, radius = ${Number(patch.radius ?? 96)}f, height = ${Number(patch.height ?? 0)}f, falloff = ${csString(patch.falloff ?? 'smooth')} },`).join('\n')}
    };

    private readonly string[] dynamicEvents = new string[] { ${dynamicEvents.map((event) => csString(event.name ?? event.id)).join(', ')} };

    private void Awake()
    {
${factionTerritory.map((name) => `        FactionControl[${csString(name)}] = 50f;`).join('\n')}
    }

    public float TerrainHeightAt(Vector2 position)
    {
        float height = 0f;
        foreach (var patch in sculptPatches)
        {
            float radius = Mathf.Max(1f, patch.radius);
            float influence = Mathf.Max(0f, 1f - Vector2.Distance(position, new Vector2(patch.x, patch.y)) / radius);
            height += patch.height * (patch.falloff == "sharp" ? influence * influence : influence);
        }
        return height;
    }

    public TerrainCollision TerrainCollisionAt(Vector2 position)
    {
        foreach (var zone in terrainZones)
        {
            if (position.x < zone.x || position.y < zone.y || position.x > zone.x + zone.w || position.y > zone.y + zone.h) continue;
            return new TerrainCollision { blocked = zone.type.Contains("hazard") || zone.type.Contains("block"), zoneId = zone.id, height = TerrainHeightAt(position) };
        }
        return new TerrainCollision { blocked = false, zoneId = "", height = TerrainHeightAt(position) };
    }

    public void AdvanceWorldTick(float deltaTime)
    {
        Tick += deltaTime;
        if (dynamicEvents.Length > 0) ActiveDynamicEvent = dynamicEvents[Mathf.FloorToInt(Tick) % dynamicEvents.Length];
        var keys = new List<string>(FactionControl.Keys);
        foreach (var key in keys) FactionControl[key] = Mathf.Clamp(FactionControl[key] + deltaTime, 0f, 100f);
    }
}
`;
  return {
    path: `${sourceBaseName(fileName)}/unity/AGDSGameViewRuntime.cs`,
    language: 'csharp',
    purpose: 'Unity scene component with terrain deformation, collision, dynamic event, weather, and faction-control hooks.',
    content,
  };
}

function buildGodotRuntimeFile(document: GameViewportDocument, fileName: string): GameEngineRuntimeGeneratedFile {
  const zonesJson = JSON.stringify(document.terrainZones ?? [], null, 2);
  const patchesJson = JSON.stringify(document.terrainSculptPatches ?? [], null, 2);
  const eventsJson = JSON.stringify((document.dynamicEvents ?? []).map((event) => event.name ?? event.id), null, 2);
  const factionJson = JSON.stringify(document.worldSimulation?.factionTerritory ?? [], null, 2);
  const content = `extends Node
class_name AGDSGameViewRuntime

# Generated by AI Game Design Studio from ${fileName}. Add this node to a scene root or autoload.
var tick := 0.0
var active_weather := ${gdString(document.worldSimulation?.weather ?? 'clear')}
var active_dynamic_event := ""
var faction_control := {}
var terrain_zones := ${zonesJson}
var sculpt_patches := ${patchesJson}
var dynamic_events := ${eventsJson}
var faction_territory := ${factionJson}

func _ready() -> void:
\tfor territory in faction_territory:
\t\tfaction_control[str(territory)] = 50.0

func terrain_height_at(position: Vector2) -> float:
\tvar height := 0.0
\tfor patch in sculpt_patches:
\t\tvar radius = max(1.0, float(patch.get("radius", 96.0)))
\t\tvar center := Vector2(float(patch.get("x", 0.0)), float(patch.get("y", 0.0)))
\t\tvar influence = max(0.0, 1.0 - position.distance_to(center) / radius)
\t\tif str(patch.get("falloff", "smooth")) == "sharp":
\t\t\tinfluence *= influence
\t\theight += float(patch.get("height", 0.0)) * influence
\treturn height

func terrain_collision_at(position: Vector2) -> Dictionary:
\tfor zone in terrain_zones:
\t\tvar x := float(zone.get("x", 0.0))
\t\tvar y := float(zone.get("y", 0.0))
\t\tvar w := float(zone.get("w", 0.0))
\t\tvar h := float(zone.get("h", 0.0))
\t\tif position.x >= x and position.y >= y and position.x <= x + w and position.y <= y + h:
\t\t\tvar zone_type := str(zone.get("type", ""))
\t\t\treturn {"blocked": zone_type.contains("hazard") or zone_type.contains("block"), "zone_id": str(zone.get("id", "")), "height": terrain_height_at(position)}
\treturn {"blocked": false, "zone_id": "", "height": terrain_height_at(position)}

func advance_world_tick(delta: float) -> Dictionary:
\ttick += delta
\tif dynamic_events.size() > 0:
\t\tactive_dynamic_event = str(dynamic_events[int(floor(tick)) % dynamic_events.size()])
\tfor key in faction_control.keys():
\t\tfaction_control[key] = clamp(float(faction_control[key]) + delta, 0.0, 100.0)
\treturn {"tick": tick, "weather": active_weather, "dynamic_event": active_dynamic_event, "faction_control": faction_control}
`;
  return {
    path: `${sourceBaseName(fileName)}/godot/agds_gameview_runtime.gd`,
    language: 'gdscript',
    purpose: 'Godot node script with terrain deformation, collision, dynamic event, weather, and faction-control hooks.',
    content,
  };
}

function buildUnrealRuntimeFiles(document: GameViewportDocument, fileName: string): GameEngineRuntimeGeneratedFile[] {
  const zones = document.terrainZones ?? [];
  const patches = document.terrainSculptPatches ?? [];
  const dynamicEvents = document.dynamicEvents ?? [];
  const factionTerritory = document.worldSimulation?.factionTerritory ?? [];
  const base = sourceBaseName(fileName);
  const header = `#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "AGDSGameViewRuntimeComponent.generated.h"

USTRUCT(BlueprintType)
struct FAGDSTerrainCollision
{
    GENERATED_BODY()
    UPROPERTY(BlueprintReadOnly) bool bBlocked = false;
    UPROPERTY(BlueprintReadOnly) FString ZoneId;
    UPROPERTY(BlueprintReadOnly) float Height = 0.f;
};

UCLASS(ClassGroup=(AGDS), meta=(BlueprintSpawnableComponent))
class UAGDSGameViewRuntimeComponent : public UActorComponent
{
    GENERATED_BODY()
public:
    UAGDSGameViewRuntimeComponent();
    UFUNCTION(BlueprintCallable) float TerrainHeightAt(FVector2D Position) const;
    UFUNCTION(BlueprintCallable) FAGDSTerrainCollision TerrainCollisionAt(FVector2D Position) const;
    UFUNCTION(BlueprintCallable) void AdvanceWorldTick(float DeltaTime);
    UPROPERTY(BlueprintReadOnly) float Tick = 0.f;
    UPROPERTY(BlueprintReadOnly) FString ActiveWeather = ${cppString(document.worldSimulation?.weather ?? 'clear')};
    UPROPERTY(BlueprintReadOnly) FString ActiveDynamicEvent;
};
`;
  const cpp = `#include "AGDSGameViewRuntimeComponent.h"

struct FAGDSRuntimeZone { const TCHAR* Id; const TCHAR* Type; float X; float Y; float W; float H; };
struct FAGDSRuntimePatch { const TCHAR* Id; float X; float Y; float Radius; float Height; bool bSharp; };

static const FAGDSRuntimeZone GAGDSTerrainZones[] = {
${zones.map((zone) => `    { TEXT(${cppString(zone.id)}), TEXT(${cppString(zone.type)}), ${Number(zone.x ?? 0)}f, ${Number(zone.y ?? 0)}f, ${Number(zone.w ?? 0)}f, ${Number(zone.h ?? 0)}f },`).join('\n')}
};

static const FAGDSRuntimePatch GAGDSSculptPatches[] = {
${patches.map((patch) => `    { TEXT(${cppString(patch.id)}), ${Number(patch.x ?? 0)}f, ${Number(patch.y ?? 0)}f, ${Number(patch.radius ?? 96)}f, ${Number(patch.height ?? 0)}f, ${patch.falloff === 'sharp' ? 'true' : 'false'} },`).join('\n')}
};

static const TCHAR* GAGDSDynamicEvents[] = { ${dynamicEvents.map((event) => `TEXT(${cppString(event.name ?? event.id)})`).join(', ')} };
static const TCHAR* GAGDSFactionTerritory[] = { ${factionTerritory.map((name) => `TEXT(${cppString(name)})`).join(', ')} };

UAGDSGameViewRuntimeComponent::UAGDSGameViewRuntimeComponent()
{
    PrimaryComponentTick.bCanEverTick = true;
}

float UAGDSGameViewRuntimeComponent::TerrainHeightAt(FVector2D Position) const
{
    float Height = 0.f;
    for (const FAGDSRuntimePatch& Patch : GAGDSSculptPatches)
    {
        const float Radius = FMath::Max(1.f, Patch.Radius);
        const float Influence = FMath::Clamp(1.f - FVector2D::Distance(Position, FVector2D(Patch.X, Patch.Y)) / Radius, 0.f, 1.f);
        Height += Patch.Height * (Patch.bSharp ? Influence * Influence : Influence);
    }
    return Height;
}

FAGDSTerrainCollision UAGDSGameViewRuntimeComponent::TerrainCollisionAt(FVector2D Position) const
{
    for (const FAGDSRuntimeZone& Zone : GAGDSTerrainZones)
    {
        if (Position.X < Zone.X || Position.Y < Zone.Y || Position.X > Zone.X + Zone.W || Position.Y > Zone.Y + Zone.H) continue;
        FAGDSTerrainCollision Result;
        Result.ZoneId = Zone.Id;
        Result.Height = TerrainHeightAt(Position);
        const FString Type = Zone.Type;
        Result.bBlocked = Type.Contains(TEXT("hazard")) || Type.Contains(TEXT("block"));
        return Result;
    }
    FAGDSTerrainCollision Result;
    Result.Height = TerrainHeightAt(Position);
    return Result;
}

void UAGDSGameViewRuntimeComponent::AdvanceWorldTick(float DeltaTime)
{
    Tick += DeltaTime;
    const int32 EventCount = UE_ARRAY_COUNT(GAGDSDynamicEvents);
    if (EventCount > 0) ActiveDynamicEvent = GAGDSDynamicEvents[FMath::FloorToInt(Tick) % EventCount];
}
`;
  return [
    {
      path: `${base}/unreal/AGDSGameViewRuntimeComponent.h`,
      language: 'cpp',
      purpose: 'Unreal ActorComponent header exposing Blueprint-callable gameview runtime hooks.',
      content: header,
    },
    {
      path: `${base}/unreal/AGDSGameViewRuntimeComponent.cpp`,
      language: 'cpp',
      purpose: 'Unreal ActorComponent source with terrain deformation, collision, dynamic event, and weather hooks.',
      content: cpp,
    },
  ];
}

function buildNativeRuntimeFiles(
  document: GameViewportDocument,
  fileName: string,
  engine: GameEngineRuntimeRequestEngine,
): GameEngineRuntimeGeneratedFile[] {
  const files: GameEngineRuntimeGeneratedFile[] = [];
  if (engine === 'unity' || engine === 'native-package') files.push(buildUnityRuntimeFile(document, fileName));
  if (engine === 'godot' || engine === 'native-package') files.push(buildGodotRuntimeFile(document, fileName));
  if (engine === 'unreal' || engine === 'native-package') files.push(...buildUnrealRuntimeFiles(document, fileName));
  files.push({
    path: `${sourceBaseName(fileName)}/ENGINE_EXPORT_README.md`,
    language: 'markdown',
    purpose: 'Import notes for engine-side terrain, world-state, collision, and dynamic-event hooks.',
    content: `# ${document.title || fileName} Engine Export

Generated by AI Game Design Studio from \`${fileName}\`.

This package provides engine-side hooks for terrain deformation, collision sampling, world ticks, weather state, dynamic events, and faction-control previews. Import the file for your engine, attach the runtime component or node to the scene controller, then connect player movement, enemy placement, HUD debug displays, and playtest probes to the exported hooks.

- Terrain height: sample sculpted terrain for traversal, cover, and camera comfort checks.
- Terrain collision: identify hazard or blocking zones for encounter readability.
- World tick: advance dynamic events, weather, and faction-control previews during playtest simulation.

The package is intentionally lightweight so designers can adapt it to project-specific physics, networking, save-state, and streaming systems.
`,
  });
  return files;
}

export function buildGameEngineRuntime(
  fileName: string,
  rawContent: string,
  request: GameEngineRuntimeRequest = {},
): GameEngineRuntimeResponse {
  let parsedJson: unknown;
  try {
    parsedJson = JSON.parse(rawContent);
  } catch (error) {
    throw new Error(`invalid game viewport JSON: ${(error as Error).message}`);
  }
  const parsed = gameViewportDocumentSchema.safeParse(parsedJson);
  if (!parsed.success) {
    const issue = parsed.error.issues[0];
    const path = issue?.path.length ? issue.path.join('.') : 'document';
    throw new Error(`invalid game viewport document at ${path}: ${issue?.message ?? 'schema validation failed'}`);
  }
  const document = parsed.data as GameViewportDocument;
  const terrainColliderCount = countTerrainColliders(document);
  const dynamicEventCount = document.dynamicEvents?.length ?? 0;
  const factionCount = document.worldSimulation?.factionTerritory?.length ?? 0;
  const requestedEngine = request.engine ?? 'webgl';
  if (requestedEngine !== 'webgl') {
    const files = buildNativeRuntimeFiles(document, fileName, requestedEngine);
    return {
      fileName,
      engine: requestedEngine,
      files,
      runtimeHooks: nativeRuntimeHooks(requestedEngine),
      terrainColliderCount,
      terrainSculptPatchCount: document.terrainSculptPatches?.length ?? 0,
      dynamicEventCount,
      factionCount,
      generatedAt: Date.now(),
    };
  }
  const runtimeHooks = [
    'window.__AGDS_GAMEVIEW_RUNTIME__.terrainHeightAt(x, y)',
    'window.__AGDS_GAMEVIEW_RUNTIME__.terrainCollisionAt(x, y)',
    'window.__AGDS_GAMEVIEW_RUNTIME__.advanceWorldTick(dt)',
    'window.__AGDS_GAMEVIEW_RUNTIME__.state',
  ];
  const title = escapeHtml(document.title || fileName);
  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${title} - AGDS WebGL Runtime</title>
  <style>
    :root { color-scheme: dark; background: #080b10; color: #e8f2ff; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
    * { box-sizing: border-box; }
    body { margin: 0; min-height: 100vh; display: grid; grid-template-rows: auto 1fr; background: #080b10; }
    header { display: flex; align-items: center; justify-content: space-between; gap: 16px; padding: 14px 18px; border-bottom: 1px solid rgba(154, 184, 216, 0.22); background: rgba(11, 17, 25, 0.92); }
    h1 { margin: 0; font-size: 15px; letter-spacing: 0; }
    header span, .debug { color: #9fb5c9; font-size: 12px; }
    main { position: relative; min-height: 0; overflow: hidden; }
    canvas { width: 100%; height: 100%; display: block; background: radial-gradient(circle at 45% 30%, #1a3340, #0a1118 62%); }
    .debug { position: absolute; left: 14px; bottom: 14px; max-width: min(560px, calc(100% - 28px)); padding: 10px 12px; border: 1px solid rgba(154, 184, 216, 0.24); background: rgba(8, 12, 18, 0.78); }
  </style>
</head>
<body>
  <header>
    <h1>${title}</h1>
    <span>AI Game Design Studio WebGL runtime - terrain collision, deformation, and live world hooks</span>
  </header>
  <main>
    <canvas id="agds-runtime-canvas" data-agds-engine="webgl-canvas" aria-label="Playable game scene runtime viewport"></canvas>
    <div class="debug" id="agds-runtime-debug">Booting WebGL game scene runtime...</div>
  </main>
  <script type="application/json" id="agds-gameview-data">${escapeHtml(JSON.stringify(document))}</script>
  <script>
(() => {
  const doc = ${safeJsonForScript(document)};
  const canvas = document.getElementById('agds-runtime-canvas');
  const debug = document.getElementById('agds-runtime-debug');
  const gl = canvas.getContext('webgl2') || canvas.getContext('webgl');
  const state = {
    tick: 0,
    activeWeather: doc.worldSimulation?.weather || 'clear',
    dynamicEventIndex: 0,
    factionControl: Object.fromEntries((doc.worldSimulation?.factionTerritory || []).map((name) => [name, 50])),
    terrainColliderCount: ${terrainColliderCount},
  };
  const patches = doc.terrainSculptPatches || [];
  const zones = doc.terrainZones || [];
  function resize() {
    const rect = canvas.getBoundingClientRect();
    const scale = window.devicePixelRatio || 1;
    canvas.width = Math.max(320, Math.floor(rect.width * scale));
    canvas.height = Math.max(240, Math.floor(rect.height * scale));
    if (gl) gl.viewport(0, 0, canvas.width, canvas.height);
  }
  function distance(a, b) {
    return Math.hypot((a.x || 0) - (b.x || 0), (a.y || 0) - (b.y || 0));
  }
  function patchSamples(patch) {
    const radius = patch.radius || 96;
    return (patch.samples && patch.samples.length ? patch.samples : [{ x: patch.x, y: patch.y, height: patch.height, radius }])
      .map((sample) => ({ x: sample.x, y: sample.y, height: sample.height, radius: sample.radius || radius }));
  }
  function terrainHeightAt(x, y) {
    let height = 0;
    for (const patch of patches) {
      for (const sample of patchSamples(patch)) {
        const radius = Math.max(1, sample.radius || patch.radius || 96);
        const influence = Math.max(0, 1 - distance({ x, y }, sample) / radius);
        if (influence <= 0) continue;
        height += sample.height * (patch.falloff === 'sharp' ? influence * influence : influence);
      }
    }
    return Number(height.toFixed(3));
  }
  function terrainCollisionAt(x, y) {
    const zone = zones.find((candidate) => {
      if (candidate.shape === 'polygon' && Array.isArray(candidate.points) && candidate.points.length > 2) {
        let inside = false;
        for (let i = 0, j = candidate.points.length - 1; i < candidate.points.length; j = i++) {
          const a = candidate.points[i], b = candidate.points[j];
          if (((a.y > y) !== (b.y > y)) && (x < ((b.x - a.x) * (y - a.y)) / ((b.y - a.y) || 1) + a.x)) inside = !inside;
        }
        return inside;
      }
      return x >= (candidate.x || 0) && y >= (candidate.y || 0) && x <= (candidate.x || 0) + (candidate.w || 0) && y <= (candidate.y || 0) + (candidate.h || 0);
    });
    return {
      blocked: Boolean(zone && /hazard|block|wall|lava|pit/i.test(String(zone.type || zone.notes || ''))),
      zoneId: zone?.id || null,
      height: terrainHeightAt(x, y),
    };
  }
  function advanceWorldTick(dt = 1) {
    state.tick += dt;
    const events = doc.dynamicEvents || [];
    if (events.length > 0) {
      state.dynamicEventIndex = Math.floor(state.tick) % events.length;
      state.activeDynamicEvent = events[state.dynamicEventIndex]?.name || null;
    }
    for (const key of Object.keys(state.factionControl)) {
      state.factionControl[key] = Math.max(0, Math.min(100, state.factionControl[key] + (events.length ? 1 : 0.25)));
    }
    return state;
  }
  function draw() {
    resize();
    if (gl) {
      gl.clearColor(0.035, 0.055, 0.08, 1);
      gl.clear(gl.COLOR_BUFFER_BIT);
    }
    advanceWorldTick(0.016);
    debug.textContent = 'WebGL runtime active - terrain colliders: ' + state.terrainColliderCount +
      ' - sculpt patches: ' + patches.length +
      ' - dynamic event: ' + (state.activeDynamicEvent || 'none') +
      ' - weather: ' + state.activeWeather;
    requestAnimationFrame(draw);
  }
  window.__AGDS_GAMEVIEW_RUNTIME__ = {
    document: doc,
    state,
    terrainHeightAt,
    terrainCollisionAt,
    advanceWorldTick,
    gl,
  };
  window.addEventListener('resize', resize);
  draw();
})();
  </script>
</body>
</html>`;

  return {
    fileName,
    engine: 'webgl-canvas',
    html,
    runtimeHooks,
    terrainColliderCount,
    terrainSculptPatchCount: document.terrainSculptPatches?.length ?? 0,
    dynamicEventCount,
    factionCount,
    ...(request.writeFileName ? { writtenFileName: request.writeFileName } : {}),
    generatedAt: Date.now(),
  };
}
