# Proprietary and confidential. Copyright (c) 2026 Greybox Studio.
@tool
extends RefCounted
class_name GreyboxFlowImporter

# Emits an autoload-ready FlowDispatcher script plus a companion scene under
# `<output_dir>/flow/`. Runtime entry point: `GreyboxFlowDispatcher.handle_event(component_id, edge_kind)`
# which calls `get_tree().change_scene_to_file(path)` for the resolved target screen.
#
# Flow edges are persisted as a JSON sidecar (`flow_edges.json`) that the dispatcher
# loads at _ready(). This keeps the GDScript output small + diffable; downstream tools
# can rewrite the JSON without touching the script.

const FLOW_SUBDIR := "flow"
const DISPATCHER_NAME := "GreyboxFlowDispatcher"


static func write_flow_dispatcher(flow_edges: Array, screen_lookup: Dictionary, output_dir: String) -> Dictionary:
    var serialized_edges := _serialize_edges(flow_edges, screen_lookup)
    var ensure := _ensure_dir(output_dir.path_join(FLOW_SUBDIR))
    if not ensure.get("succeeded", false):
        return {"succeeded": false, "message": ensure.get("message", "")}

    var edges_path := output_dir.path_join(FLOW_SUBDIR).path_join("flow_edges.json")
    var edges_file := FileAccess.open(edges_path, FileAccess.WRITE)
    if edges_file == null:
        return {"succeeded": false, "message": "Could not write Greybox flow edges to %s." % edges_path}
    edges_file.store_string(JSON.stringify(serialized_edges, "\t"))
    edges_file.close()

    var script_path := output_dir.path_join(FLOW_SUBDIR).path_join("flow_dispatcher.gd")
    var script_file := FileAccess.open(script_path, FileAccess.WRITE)
    if script_file == null:
        return {"succeeded": false, "message": "Could not write Greybox flow dispatcher to %s." % script_path}
    script_file.store_string(_dispatcher_source(edges_path))
    script_file.close()

    var scene_path := output_dir.path_join(FLOW_SUBDIR).path_join("flow_dispatcher.tscn")
    var scene_save := _write_dispatcher_scene(scene_path, script_path)
    if not scene_save.get("succeeded", false):
        return scene_save

    return {
        "succeeded": true,
        "script_path": script_path,
        "scene_path": scene_path,
        "edges_path": edges_path,
        "edge_count": serialized_edges.size(),
        "message": "Wrote %d flow edges to %s and dispatcher to %s." % [serialized_edges.size(), edges_path, script_path]
    }


static func autoload_singleton_name() -> String:
    return DISPATCHER_NAME


static func _serialize_edges(flow_edges: Array, screen_lookup: Dictionary) -> Array:
    var entries: Array = []
    for edge in flow_edges:
        if typeof(edge) != TYPE_DICTIONARY:
            continue
        var trigger := edge.get("trigger", {})
        var component_ref := ""
        var trigger_type := ""
        if typeof(trigger) == TYPE_DICTIONARY:
            trigger_type = str(trigger.get("type", ""))
            component_ref = str(trigger.get("componentRef", ""))
        var to_screen := str(edge.get("to", ""))
        entries.append({
            "id": str(edge.get("id", "")),
            "from": str(edge.get("from", "")),
            "to": to_screen,
            "to_scene": str(screen_lookup.get(to_screen, "")),
            "trigger_type": trigger_type,
            "component_ref": component_ref,
            "event_id": str(trigger.get("eventId", "")) if typeof(trigger) == TYPE_DICTIONARY else "",
            "condition": str(edge.get("condition", "")),
            "delay_seconds": float(trigger.get("delaySeconds", 0.0)) if typeof(trigger) == TYPE_DICTIONARY else 0.0
        })
    return entries


static func _dispatcher_source(edges_path: String) -> String:
    return """# Proprietary and confidential. Copyright (c) 2026 Greybox Studio.
# Generated by GreyboxFlowImporter -- do not edit by hand. Rewrite via the importer.
@tool
extends Node
class_name GreyboxFlowDispatcher

const EDGES_PATH := \"%s\"
var edges: Array = []

func _ready() -> void:
    var file := FileAccess.open(EDGES_PATH, FileAccess.READ)
    if file == null:
        push_warning(\"GreyboxFlowDispatcher could not load %%s\" %% EDGES_PATH)
        return
    var body := file.get_as_text()
    file.close()
    var parsed := JSON.parse_string(body)
    if typeof(parsed) == TYPE_ARRAY:
        edges = parsed


func handle_event(component_id: String, edge_kind := \"tap\") -> bool:
    for edge in edges:
        if typeof(edge) != TYPE_DICTIONARY:
            continue
        var trigger_type := str(edge.get(\"trigger_type\", \"\"))
        if trigger_type != edge_kind and edge_kind != \"\" and trigger_type != \"\":
            continue
        if str(edge.get(\"component_ref\", \"\")) != component_id:
            continue
        var to_scene := str(edge.get(\"to_scene\", \"\"))
        if to_scene.is_empty():
            return false
        return _go_to_scene(to_scene)
    return false


func handle_script_event(event_id: String) -> bool:
    for edge in edges:
        if typeof(edge) != TYPE_DICTIONARY:
            continue
        if str(edge.get(\"trigger_type\", \"\")) != \"scriptEvent\":
            continue
        if str(edge.get(\"event_id\", \"\")) != event_id:
            continue
        return _go_to_scene(str(edge.get(\"to_scene\", \"\")))
    return false


func resolve_target(component_id: String, edge_kind: String) -> String:
    for edge in edges:
        if typeof(edge) != TYPE_DICTIONARY:
            continue
        if str(edge.get(\"component_ref\", \"\")) != component_id:
            continue
        if not edge_kind.is_empty() and str(edge.get(\"trigger_type\", \"\")) != edge_kind:
            continue
        return str(edge.get(\"to_scene\", \"\"))
    return \"\"


func _go_to_scene(scene_path: String) -> bool:
    if scene_path.is_empty():
        return false
    var tree := get_tree()
    if tree == null:
        return false
    var error := tree.change_scene_to_file(scene_path)
    return error == OK
""" % edges_path


static func _write_dispatcher_scene(scene_path: String, script_path: String) -> Dictionary:
    var root := Node.new()
    root.name = DISPATCHER_NAME
    var script := load(script_path)
    if script == null:
        # In headless tooling the script file is brand new and load() might miss
        # it because Godot has not scanned the filesystem yet. We'll set the
        # script_path via metadata so the scene knows where to attach at runtime.
        root.set_meta("greybox_pending_script", script_path)
    else:
        root.set_script(script)

    var packed := PackedScene.new()
    var pack_error := packed.pack(root)
    if pack_error != OK:
        return {"succeeded": false, "message": "Could not pack flow dispatcher (code %d)." % pack_error}
    var save_error := ResourceSaver.save(packed, scene_path)
    if save_error != OK:
        return {"succeeded": false, "message": "Could not save flow dispatcher to %s (code %d)." % [scene_path, save_error]}
    return {"succeeded": true, "message": ""}


static func _ensure_dir(path: String) -> Dictionary:
    var globalized := ProjectSettings.globalize_path(path)
    var directory_error := DirAccess.make_dir_recursive_absolute(globalized)
    if directory_error != OK:
        return {"succeeded": false, "message": "Could not create Greybox flow directory %s (code %d)." % [path, directory_error]}
    return {"succeeded": true, "message": ""}
