import { build } from "esbuild";

await build({
  bundle: true,
  entryNames: "[dir]/[name]",
  entryPoints: [
    "./src/index.ts",
    "./src/critique.ts",
    "./src/api/connectionTest.ts",
    "./src/api/orbit.ts",
    "./src/api/product-analytics.ts",
    "./src/api/pro-modules.ts",
    "./src/api/finalize.ts",
    "./src/api/files.ts",
    "./src/api/marketplace.ts",
    "./src/api/providerModels.ts",
    "./src/api/projects.ts",
    "./src/api/research.ts",
    "./src/game-telemetry-sdk.ts",
    "./src/game-studio.ts",
    "./src/media/models.ts",
    "./src/prompts/discovery.ts",
    "./src/prompts/directions.ts",
    "./src/prompts/media-contract.ts",
    "./src/prompts/system.ts",
  ],
  format: "esm",
  outbase: "./src",
  outdir: "./dist",
  outExtension: { ".js": ".mjs" },
  packages: "external",
  platform: "node",
  target: "node24",
});
